#!/usr/bin/env python
"""Install Console Launch Application

This file is used for launching the application.

Changes the current working directory to the program directory and launches the GUI application.
"""

import GUI
import os
import sys


__version__ = '1.1.4'

if __name__ == '__main__':
    os.chdir(sys.path[0])
    GUI.initialize()
